
export const labels = {
   // states
   openState: "data-fn-is-open",
   loadingState: "data-fn-is-loading",
   // shared
   target: "data-fn-target",
   overlay: "data-fn-overlay",
   hideBodyOverflow: "data-fn-hide-body-overflow",
   // menu
   menuItem: "data-fn-menu-item",
   menuList: "data-fn-menu-list",
   menuSubmenu: "data-fn-submenu",
   menuButton: "data-fn-menu-button",
   menuBack: "data-fn-menu-back",
   // accordions
   accordions: "data-fn-accordion",
   // dropdown
   dropdownText: "data-fn-dropdown-text",
   // modals
   modalButton: "data-fn-modal-button",
   modalBox: "data-fn-modal-box",
   modalClose: "data-fn-modal-close",
   // tabs
   tabs: "data-fn-tabs",
   tabsHeading: "data-fn-tabs-heading",
   tabsContent: "data-fn-tabs-content",
   tabsClose: "data-fn-tabs-content",
   // load more
   loadMorePage: "data-fn-load-more-page",
   // autocomplete
   autocompleteWrapper: "data-fn-autocomplete-wrapper",
   autocompleteInput: "data-fn-autocomplete-input",
   autocompleteSubmit: "data-fn-autocomplete-submit",
   autocompleteResults: "data-fn-autocomplete-results",
   autocompleteResultsInner: "data-fn-autocomplete-results-inner",
   autocompleteTemplate: "data-fn-autocomplete-template",
   // nav
   navPanel: "data-fn-nav-panel",
   navButton: "data-fn-nav-button",
   navOpen: "data-fn-nav-open",
   navClose: "data-fn-nav-close",
   // filters
   tagId: "data-fn-tag-id",
   tagTemplate: "data-fn-tag-template",
   tagRow: "data-fn-tag-row",
   tagContent: "data-fn-tag-content",
   filterGroup: "data-fn-filter-group"
}
